version: '3.8'
services:
  mysql-container:
    container_name: mysql-container
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: containers
    ports:
      - "3307:3306"

  spring-app:
    image: spring-boot-app:latest
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql-container
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
      MYSQL_PORT: 3306